version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todays-menu-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1acde1v1expsc"
s3_prefix = "todays-menu-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
