AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: todays-menu-api

Resources:
  TodaysMenuApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap.is.the.handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      Timeout: 10
      Environment:
        Variables:
          AWS_PROFILE: default
          AUTH_PRIVATE_KEY: ""
          CORS_ORIGIN: ""
      Events:
        Index:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref GraphApi
        GraphQL:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
            RestApiId: !Ref GraphApi
        GraphQLOptions:
          Type: Api
          Properties:
            Path: /graphql
            Method: options
            RestApiId: !Ref GraphApi
  GraphApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      BinaryMediaTypes:
        - "multipart~1form-data"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloRustApi:
    Description: "API Gateway endpoint URL for Prod stage for TodaysMenuApiFunction"
    Value: !Sub "https://${GraphApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  TodaysMenuApiFunction:
    Description: "TodaysMenuApiFunction ARN"
    Value: !GetAtt TodaysMenuApiFunction.Arn
  TodaysMenuApiFunctionIamRole:
    Description: "Implicit IAM Role created for TodaysMenuApiFunction"
    Value: !GetAtt TodaysMenuApiFunctionRole.Arn
